### ISSUE TITLE
Проблема при реализации аутентификации пользователя

### ISSUE THREAD

**Issue by marijarin** [Marijarin/andin-homeworks#9]
Здравствуйте,
**1 Проблема.**
Хотела реализовать аутентификацию пользователя (вход, регистрацию) через Dialog Fragment, пользуясь документацией по ссылке [https://developer.android.com/develop/ui/views/components/dialogs#ShowingADialog](https://developer.android.com/develop/ui/views/components/dialogs#ShowingADialog)
Подумала, что будет лучше реализовать через коллбек в FeedFragment, чтобы он получал данные от диалога, тем более в нем есть authModel. Для этого согласно документации надо было переопределить методы из интерфейса DialogListener, что я и стала делать в FeedFragment():
override fun onDialogSignInClick(dialog: DialogFragment) {
        authViewModel.updateUser(********)
    }

    override fun onDialogSignUpClick(dialog: DialogFragment) {

    }

    override fun onDialogNegativeClick(dialog: DialogFragment) {
        findNavController().navigateUp()
    }
но мне надо передать логин и пароль (вместо *******) в  authViewModel.updateUser(******). Не пойму, как их взять. Контекст диалога прикрепляется к FeedFragment() через
override fun onAttach(context: Context) {
        super.onAttach(context)
но как достать логин и пароль, если View у него создается через билдер и биндинга нет, чтобы считать текст. Но ведь как-то же его считывают. Так что здесь пока не соображу, как передать аргументы в функцию  authViewModel.updateUser(********).

**2 Проблема.**
Также внезапно компилятор создал проблему, тоже не знаю, как быстро ее исправить. Он перестал отличать textArg в разных Bundle (см.скриншоты). Я могу, конечно, попробовать передавать ИД поста, чтобы достать вложение (тогда тип arguments  у Bundle изменится), но раньше ведь все работало и компилятор отличал один textArg от другого. Есть ли решение этой проблемы, чтобы не переделывать существенно код?
![image](https://user-images.githubusercontent.com/106971617/210135096-f093a55e-5f68-46ca-8a56-87fe637475ce.png)
![image](https://user-images.githubusercontent.com/106971617/210135113-20aaa371-7a31-4de4-b0b5-0340b28a5c50.png)

Это случилось, когда я вынесла authViewModel в свойства фрагмента. Но когда я вернула, компилятор все равно помечал textArg в разных Bundle как ошибку
![image](https://user-images.githubusercontent.com/106971617/210135184-67d90ec9-c562-4b5f-8c95-b30413492da7.png)

**Comment by Onotole1** [comment]
Здравствуйте! Если вы хотите представить фрагменты входа и регистрации как диалоги, то
1) Наследуйтесь не от Fragment, а от DialogFragment
```
class SignInFragment : DialogFragment()
```
2) Поменяйте в навигации fragment на dialog
```
<dialog
        android:id="@+id/signInFragment"
        android:name="ru.netology.nmedia.activity.SignInFragment"
        android:label="SignInFragment" />
```
У вас останется доступ к binding, AuthViewModel и всему, что необходимо для входа прямо из диалога

По поводу конфликтов импортов - назовите эти экстеншены как-нибудь по-разному) Например, imageTextArg, newPostTextArg
